name: Deploy Multiple Lambdas

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lambda:
          - name: lambdas/test
            function: test
          - name: lambdas/collect_current_contract_data
            function: collect_current_contract_data

    env:
      AWS_REGION: us-east-2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies and build Lambda Layer
        id: build_layer
        run: |
          mkdir -p ${{ matrix.lambda.name }}/python
          pip install -r ${{ matrix.lambda.name }}/requirements.txt -t ${{ matrix.lambda.name }}/python/
          cd ${{ matrix.lambda.name }}
          zip -r ../${{ matrix.lambda.function }}_layer.zip python/
        shell: bash

      - name: Publish Lambda Layer
        id: publish_layer
        run: |
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name ${{ matrix.lambda.function }}-layer \
            --zip-file fileb://${{ matrix.lambda.function }}_layer.zip \
            --compatible-runtimes python3.10 \
            --region $AWS_REGION \
            --query 'LayerVersionArn' \
            --output text)
          echo "LAYER_ARN=$LAYER_ARN" >> $GITHUB_ENV

      - name: Package Lambda Function
        run: |
          cd ${{ matrix.lambda.name }}
          zip ../../${{ matrix.lambda.function }}.zip lambda_function.py
        shell: bash

      - name: Deploy Lambda Code
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.lambda.function }} \
            --zip-file fileb://${{ matrix.lambda.function }}.zip \
            --region $AWS_REGION

      - name: Attach Lambda Layer
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ matrix.lambda.function }} \
            --layers ${{ env.LAYER_ARN }} \
            --region $AWS_REGION





      # - name: Install Dependencies and Package Lambda
      #   run: |
      #     cd ${{ matrix.lambda.name }}
      #     mkdir -p build
      #     pip install -r requirements.txt -t build/
      #     cp lambda_function.py build/
      #     ZIP_NAME=$(basename "${{ matrix.lambda.name }}").zip
      #     cd build
      #     zip -r ../../$ZIP_NAME .
      #     cd ../..

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Deploy to AWS Lambda
      #   run: |
      #     aws lambda update-function-code \
      #       --function-name ${{ matrix.lambda.function }} \
      #       --zip-file fileb://${{ matrix.lambda.name }}.zip
