name: Deploy Multiple Lambdas

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lambda:
          # - name: lambdas/test
          #   function: test
          - name: lambdas/PuckPedia/collect_current_contract_data
            function: collect_current_contract_data
          - name: lambdas/PuckPedia/collect_historical_contract_data
            function: collect_historical_contract_data
          - name: lambdas/PuckPedia/get_player_ids
            function: get_player_ids

          - name: lambdas/NHLAPI/collect_player_information
            function: collect_player_information


    env:
      AWS_REGION: us-east-2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies and build Lambda Layer
        id: build_layer
        run: |
          mkdir -p ${{ matrix.lambda.name }}/python
          pip install -r ${{ matrix.lambda.name }}/requirements.txt -t ${{ matrix.lambda.name }}/python/
          cd ${{ matrix.lambda.name }}
          zip -r ../../../${{ matrix.lambda.function }}_layer.zip python/
        shell: bash

      - name: Publish Lambda Layer
        id: publish_layer
        run: |
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name ${{ matrix.lambda.function }}-layer \
            --zip-file fileb://${{ matrix.lambda.function }}_layer.zip \
            --compatible-runtimes python3.10 \
            --region $AWS_REGION \
            --query 'LayerVersionArn' \
            --output text)
          echo "LAYER_ARN=$LAYER_ARN" >> $GITHUB_ENV

      - name: Package Lambda Function
        run: |
          cd ${{ matrix.lambda.name }}
          zip ../../../${{ matrix.lambda.function }}.zip lambda_function.py
        shell: bash

      - name: Deploy Lambda Code
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.lambda.function }} \
            --zip-file fileb://${{ matrix.lambda.function }}.zip \
            --region $AWS_REGION

      - name: Wait for Lambda to be ready
        run: |
          for i in {1..10}; do
            status=$(aws lambda get-function-configuration --function-name ${{ matrix.lambda.function }} --query 'LastUpdateStatus' --output text)
            if [ "$status" == "Successful" ]; then
              echo "Lambda is ready"
              exit 0
            fi
            echo "Waiting for Lambda update to complete. Status: $status"
            sleep 5
          done
          echo "Timeout waiting for Lambda update to complete"
          exit 1

      - name: Attach Lambda Layer
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ matrix.lambda.function }} \
            --layers ${{ env.LAYER_ARN }},arn:aws:lambda:us-east-2:336392948345:layer:AWSSDKPandas-Python311:17 \
            --region $AWS_REGION

