name: Deploy Multiple Lambdas

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lambda:
          - name: lambdas/test
            function: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies and Package Lambda
        run: |
          cd ${{ matrix.lambda.name }}
          mkdir -p build
          pip install -r requirements.txt -t build/
          cp lambda_function.py build/
          ZIP_NAME=$(basename "${{ matrix.lambda.name }}").zip
          cd build
          zip -r ../../$ZIP_NAME .
          cd ../..

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.lambda.function }} \
            --zip-file fileb://${{ matrix.lambda.name }}.zip
